version: '3'
services:
  postgres:
    image: postgres
    container_name: todolist-dev-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      TZ: 'Asia/Saigon'
      PGTZ: 'Asia/Saigon'
    ports:
      - ${DATABASE_PORT:-5436}:5432
