name: Deploy Todolist Backend to Staging

on:
  push:
    branches: ['main']

env:
  APP_ENV: ${{ secrets.STAGING }}

jobs:
  build:
    runs-on: [self-hosted, staging]

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Delete old env file
        run: rm -r -f .env

      - name: Create env_temp file
        run: touch .env_temp

      - name: Copy Secret Key Multiline environment variable to .env_temp file
        run: echo $APP_ENV | tee .env_temp

      - name: Replace space character with break-line in .env
        run: sed 's/ /\n/g' .env_temp >> .env

      - name: Remove .env_temp file
        run: rm -r -f .env_temp

      - name: Install Yarn and env-cmd
        run: npm install -g yarn env-cmd && yarn

      - name: Migrations
        continue-on-error: true
        run:
          yarn typeorm migration:run -d src/configs/data-source.ts

          # Reference from offical Docker youtube channel: https://youtu.be/aNh8iShFXto
      - name: Build Docker and deployment
        run: sudo chmod +x docker-build.sh && sudo ./docker-build.sh

      - name: Prune docker cache all
        continue-on-error: true
        run: sudo docker system prune -f -a --volumes
